<?php
// Person A owns this file (page shell only).
// Person B: link your stylesheet below and swap scores.mock.js for scores.js.
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Fifteen Puzzle</title>
  <link rel="stylesheet" href="css/style.css">
</head>
<body>

<main>
  <h1>Fifteen Puzzle</h1>

  <section id="controls" aria-label="Game controls">
    <label for="mode">Mode</label>
    <select id="mode">
      <option value="numbers">Numbers</option>
      <option value="theme-a">Theme A</option>
      <option value="theme-b">Theme B</option>
    </select>

    <button id="shuffle" type="button">Shuffle</button>
    <button id="magic" type="button">Magic (<span id="magic-left">3</span>)</button>
  </section>

  <!-- Tiles are generated by js/game.js -->
  <div id="board" class="board mode-numbers" role="grid" aria-label="Puzzle board"></div>

  <section id="stats" aria-live="polite">
    <p>Moves: <strong id="moves">0</strong></p>
    <p>Time: <strong id="time">0:00</strong></p>
    <p id="status" role="status"></p>
  </section>

  <!-- Person B: leaderboard renders here -->
  <section id="leaderboard" aria-label="High scores"></section>
</main>

<script src="js/scores.mock.js"></script>
<script src="js/puzzle.js"></script>
<script src="js/game.js"></script>
</body>
</html>
